project:
  type: book
  output-dir: docs



book:
  title: "MA40001"
  author: "Philip Murray"
  date: "11/22/2024"
  downloads: pdf
  repo-actions: [issue]
  cover-image: MA32009Cover.png


  
  chapters:
    - index.qmd
    - part: "Markdown"
      chapters: 
        - index.qmd
    - part: "Python"
      chapters:
        - index.qmd

      
format:
  html:
    theme: cosmo
    code-fold: true
  pdf:
    documentclass: scrreprt
    echo: false
    include-in-header:
      - text: |
          \usepackage{chemarr}
          \usepackage{lipsum}
          \usepackage{tikz}
          \AtBeginDocument{\thispagestyle{empty}
          \begin{tikzpicture}[remember picture,overlay]
          \node at (current page.center) {\includegraphics[width=\paperwidth,height=\paperheight,keepaspectratio]{MA32009Cover.png}};
          \end{tikzpicture}\clearpage}

execute:
  warning: false
     


  



