project:
  type: book
  output-dir: docs
  render:
    - index.qmd
    - LectureSlides.qmd
  resources:
    - LectureSlides.pdf

book:
  title: "MA40001"
  author: "Philip Murray"
  date: "10/09/2024"
  downloads: pdf
  repo-actions: [issue]
  
  chapters:
    - index.qmd
    - Software.qmd
    - CommunicatingMathematics.qmd 
    - QuartoIntroduction.qmd
    - MathematicalTypesetting.qmd
    - Python.qmd
    - VersionControl.qmd
    - Presentations.qmd
  
      
format:
  html:
    theme: cosmo
    code-fold: true
  pdf:
    documentclass: scrreprt
    echo: false
    include-in-header:
      - text: |
          \usepackage{chemarr}
          \usepackage{lipsum}
          \usepackage{tikz}
          \AtBeginDocument{\thispagestyle{empty}
          \begin{tikzpicture}[remember picture,overlay]
          \node at (current page.center) {\includegraphics[width=\paperwidth,height=\paperheight,keepaspectratio]{MA32009Cover.png}};
          \end{tikzpicture}\clearpage}
  gfm:
    mermaid-format: png
execute:
  warning: false
  freeze: auto  # re-render only when source changes
     


  



