# Preface {.unnumbered}


Welcome to the module MA40001. 

My name is Philip Murray and I am the module lead.

## How to contact me?

* email: pmurray@dundee.ac.uk
* office: G11, Fulton Building
* Teams: PM me


## Software

The taught component on the module will require you to use:

* Quarto
* Visual Studio Code
* Github
* latex
* python


::: {.callout-note}
# Why bother with all this?

The aim is to provide you with *open-source* tools that enable you to generate modern scientific/mathematical documents.

:::


### Uni machines

From Apps Anywhere, open:

* VS Code with Quarto XXX 



### On your own machine
Install
 * Quarto
 * VS Code 
 * Python + libraries (matplotlib.pyplot, numpy,)

 Within Quarto:
 * install the quarto extension for VS Code
 * install Latex (follow Quarto instruction for generating a pdf).
 * Configure the Python interpreter (Show and Run Commands->Python Select Interpreter)


## Content

### Lecture notes
You can find lecture notes for the module on this page. If you would like a pdf this can be easily generated by clicking on the pdf link of the  webpage. I will occasionally edit/update the notes as we proceed through lectures. If you spot any errors, typos or omissions please Raise an Issue

### Template codes

 I have provided template codes via the github page dundeemath/MA40001resources.

We are using github classroom. Hence you you each have a private github repository (which only I can see the content of).

The idea is that you *pull* documents from github, edit them as necessary and *push* the edited documents back to github.





## Python codes

I have provided Python codes for most of the figures in the notes (you can unfold code section by clicking `Code'). Note that the Python code does not appear in the pdf.

 Many of you have taken the Introduction to Programming module at Level 2 and have therefore some experience using Python. I strongly encourage you to use the provided codes as a tool to play around with numerical solutions of the various models that we will be working on. The codes should run as standalone Python codes (e.g. Paste into Anaconda->Spyder).

 
## Assessment

* Presentation
* Interim report
* Poster 
* Final report
* Viva


## Plan

| Week | Material | Assessment |
|-------|:---|-----| ---|
| 1-3    | Quarto  | Formative |
| 4-6     | Python | Formative |
| 7-10     | Presentation practices  |   Formative |  
| 11     | Assessed presentation  | Summative|   
: Module organisation

