---
title: "MA40001"
author: "Philip Murray"
format: beamer
---

# Week 5

## Recap

1. Quarto 
    * Using Quarto to render .qmd file into .html and .pdf formats
    * Add document elements (sections,figures,tables, cross references, citations, schematic diagrams etc.)
\pause 

2. Python
    * Integrate Python code in a Quarto document
    * Use Python libraries
\pause 

3. Github 
    * Create and clone repositories
    * Fetch,pull, commit and push
    * Fork repositories

4. Install VSCode/Python/Github on your own computer/H1 desktop.

##  Feedback on your submissions

1. Strip out figures/table/appendices. Does the writing stand alone,i.e. is there a coherent narrative to the presented work?
\pause
2. Figures/tables should appear after they are first introduced in the text.
\pause
3. Submit a pdf!
\pause
4. Equations require punctuation.
\pause
5. What makes a good figure caption?
\pause
6. Mathematical functions: $\sin(x)$ rather than $sin(x)$.


## Tasks for this week

1. *Fork* blog and final report templates from github
2. Using the terminal in VSCode to render blog and final report (see bottom of Chapter 3).
4. Use Python libraries (e.g. Pandas, Matplotlib, numpy, sympy, scipy).


##  Plagiarism

Plagiarism is the unacknowledged use of another’s work as if it were one’s own. Examples are: 

* the inclusion of more than a single phrase from another's work without the use of quotation marks and acknowledgement of the source;
\pause 
* summarising another's work by changing a few words or altering the order of presentation without acknowledgement; 
\pause 
* copying another's work; 
\pause 
* the use of another's ideas without acknowledgement.


## References

Unless otherwise stated, it is assumed that any presented work is your own. 

\pause 
* Use references to attribute work to others
\pause 
* Reference primary sources (e.g. textbooks, papers as they have permanent bibliographic records) where possible.
\pause 
*  code that you have not written must be referenced.

## Generative AI

Generative AI uses statistical patterns in data upon which it has been trained to provide responses to natural language queries.

You might use it:

* to generate graphics/visual content
* to summarise long texts to check your understanding
* as a debating partner
* to generate questions from an article/text to check your understanding
* for debugging code
* for improving grammar

## Problems with using generative AI

1. We want to develop critical thinking and problem solving skills!
\pause
2. You are expected to defend the choices/methods/techniques that you use.
\pause
3. Generative AI can sound convincing but be factually incorrect (e.g. references)
\pause
4. Using generative AI to generate content without attributing the source is a form of plagiarism. 

## AI statement (University policy)

1. Fill in an AI statement in report appendix
2. Provide a record of 
    * prompts
    * responses
    * how you used the output.
3. Be able to defend the work that you present (presentation/poster/viva).



# Week 4

## Tasks


1. Install software on H1 pc (see Chapter 1)
2. Learn to use github for file management (see Chapter 6 in notes)
3. Continue with Python exercises (Chapter 5)
4. Learn how to write a blog using the template
5. Submit a pdf: a quarto write up of your work so far in Python.



# Week 3

## Tasks


General:

* If you do not already have one, sign up for an account on https:://github.com. We will use this next week.
* Install VSCode on your personal computer. Then install the Quarto extension on VSCode. 
* Fill in feedback form linked on MyDundee announcement.


Python:

* Start embedding Python codes in your Quarto document 
* Work through the exercises up to for loops and if statements.

# Week 2

## Tasks

Use Quarto to generate a pdf with:

* title, author 
* section headings
* figures
* tables
* equations using latex
* schematic diagrams
* cross referencing of different objects
* bibliography
* appendices

## Project narrative (suggestion)

 * One sentence summary of your project
 * Why is the topic important?
 * What is the background to your project (place the work in historical context)?
 * What are the project Aims?
 * What work did you do to address the Aims?
 * Outlook, reflection (recap the project, were the aims addressed?, what are the limitations of the work? what would come next?)

 Disclaimer: there are other ways to structure a project narrative. Discuss this with your project supervisor.


 



# Weeks 1 and 2
## Tasks 

- Get assigned your project
- Set up a meeting with your project supervisor
- Devise a plan for how you are going to work on your project
- Read Chapter 1 of lecture notes
- Start using Quarto (Chapter 2 of lecture notes)



## Modules Aims:

* investigate a new mathematical topic
* develop communication skills
* develop independent study skills
* critical analysis
* develop programming skills

##  Module Structure


### Your project content

* work independently 
* meet with your project supervisor (you need to discuss and arrange a meeting schedule).

### Writing/presentation

* weekly sessions developing communication/writing/programming skills (see timetable).


### Optional

* 2 p.m. on Monday is Maths seminar - you are encouraged to attend but it is optional.



## Module assessment

* presentation (10%)
* interim report (15%)
* poster (10%)
* final report + *viva* (65%)

Template projects and presentations will be available.

## How did projects get assigned?

* Algorithm maximises overall satisfaction (tries to get as many students as high up preference list as possible) and is constrained by supervisor workload
* If you are not satisfied, please come and discuss with me.

## Feedback 

* Formative assessment. You will receive feedback 
    * on submitted weekly work
    * practice presentation sessions
    * from your supervisor in meetings
    * documents that your supervisor reads in advance of submission
* Summative assessment
    * You will receive an email with grades and feedback from examiners

## Any potential issues

* It's a 30 credit module
* Speak with your project supervisor
* Come and speak with me
* SSLC

