---
title: "Typesetting mathematics"
format:
  html:
    code-fold: true
  pdf:
    code-fold: true    
jupyter: python3
---

#  The math environment in latex
Latex is a programming language used for mathematical typesetting. In its original form a latex file is compiled to generate a .pdf file. Mathematical notation is written in the 'math environment'. You can find a detailed introduction to latex [here](https://tug.ctan.org/info/short-math-guide/short-math-guide.pdf).

Within Quarto we can access the latex math environment by enclosing text within dollar symbols. 

To typeset mathematics inline (e.g. $x+y=2$) we write ...

``` markdown
To typeset mathematics in line (e.g. $x+y=2$) we write ...
```


To typeset mathematics in a new line we use double dollar symbols. To obtain the expression
$$
\frac{x+y}{2}=4,
$$
we write
``` markdown

$$
\frac{x+y}{2}=4.
$$
```


It is worth spending some time familiarising yourself with basic latex commands. 

An very simple equation, $ f(x) \epsilon > 0$,  inserted in a line of  text (inline). The dollar sign switches between maths mode and text mode. 

An equation separate from the text without equation number
$$  \epsilon > 0. $$

The same equation with an equation number
$$
 \epsilon > 0. 
 $$ {#eq-myequation}



Here is an array of equations
$$
\begin{eqnarray}
\sum_1^3 n &=& 1+ 2 + 3 \nonumber \\
&  = & 6 \\
\sum_1^4 n &=& 1+2 +3 +4 \nonumber  \\
& = & 10
\end{eqnarray}
$$
Note that the equations are aligned such that the equal signs within the ampersands are at the same place. 

More examples:
$$ \lim_{n \to \infty} \sum_{k=1}^n \frac{1}{k^2} = \frac{\pi^2}{6} $$

$$\begin{equation} x^{2} \geq 0\qquad \textrm{for all }x\in\mathbb{R} \end{equation}$$

Several expressions separated by some space
$$
\begin{equation}
\sqrt{ x^{2}+\sqrt{y} } \quad \overline{m+n} \quad \underbrace{ a+b+\cdots+z }_{26} 
\end{equation}
$$

$$
\begin{equation}
 \mathbf{X} = \left( \begin{array}{ccc} x_{11} & x_{12} & \ldots \\ x_{21} & x_{22} & \ldots \\ \vdots & \vdots & \ddots \end{array} \right) 
 \end{equation}
$$ 

$$
\begin{equation} y = \left\{ \begin{array}{ll}
a & \textrm{if $d>c$}\\ b+x &  \textrm{in the morning}\\ l & \textrm{all day long}
\end{array} \right. 
\end{equation}
$$
More on brackets:

$$
\begin{eqnarray} 
& &  (4)  \\
& & (\frac{4}{3}) \leftarrow \textrm{this is bad} \\
& & \left(\frac{4}{3} \right)  \leftarrow \textrm{much better}
\end{eqnarray}
$$


## Exercise: an example worksheet
Try to typeset the questions below in latex:




1. Denote the roots of the equation $x^2+5x+1=0$ by $x_1=\alpha$ and $x_2=\beta$.
2. 
$$
 \sin \left(3\theta+\frac{\pi}{2} \right)=\frac{1}{2} \qquad   0\le
\theta \leq \pi .
$$


3. 
Express ${\displaystyle \frac{2x-26}{x^2-2x-8}}$ in partial fractions.


4. $$
\mbox{\bf (a)}\; \sum_{k=1}^{500} (2k-21),\qquad
\mbox{\bf (b)}\; \sum_{k=1}^{20} \frac{(-2)^k}{5},\qquad
\mbox{\bf (c)}\; \sum_{k=1}^\infty 5\left(\frac{1}{3}\right)^k.
$$



5.
$$
\int_0^{1/2} x\sqrt{1-2x}dx.
$$


6.
$$
\frac{\partial v}{\partial t}=\frac{\partial^2 v}{\partial x^2}
+v^2(1-v)\qquad  x\in\mathbb{R}, \;\; t>0.
$$

7.
$$
\begin{eqnarray}
\frac{\partial u}{\partial t} & = & (a - u + u^2v ) +
\frac{\partial^2 u}{\partial x^2}, \nonumber \\
\frac{\partial v}{\partial t} & = & (b - u^2v ) +
d \frac{\partial^2 v}{\partial x^2}, \nonumber 
\end{eqnarray}
$$


9. 
$$\begin{eqnarray}
n_{t} &=&-(nu_t)_x+rn(1-n),\nonumber\\ \label{eqn1}
N u_{xx} + (\tau n\rho)_x&=&s\rho u,\nonumber \\
\rho_t+(\rho u_t)_x&=&0,\nonumber
\end{eqnarray}
$$

10.
$$
I(t)=\left\{
\begin{array}{ll}
I_0(t), & 0\leq t < \tau, \\
I_0(t)+S(0)-S(t-\tau), & \tau \leq t < \tau+\sigma, \\
S(t-\tau-\sigma)-S(t-\tau), & \tau+\sigma \leq t,
\end{array}
\right.
$$

11.
$$
\begin{equation}
  A  =  \left[ 
\begin{array}{rrr}
  0  &  5  &  -2   \\ 
  5  & -7  &   5   \\ 
 -2  &  5  &   0
\end{array}
\right] . 
\end{equation}
$$


13. 
$$
f(x)=\left\{
\begin{array}{ll} x^2 \quad & x<0 \\ \sqrt{x+1} & x\geq 0 \end{array}
\right.
$$

14. 

$$
x^2+4x+4=0.
$$ {#eq-quadratic}

Equation @eq-quadratic is a quadratic. 














